// Code generated by ogen, DO NOT EDIT.

package client

// OperationName is the ogen operation name
type OperationName = string

const (
	GetStatusOperation  OperationName = "GetStatus"
	PostLockOperation   OperationName = "PostLock"
	PostUnlockOperation OperationName = "PostUnlock"
)
