// Code generated by ogen, DO NOT EDIT.

package client

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetStatus implements get-status operation.
//
// Get status.
//
// GET /status
func (UnimplementedHandler) GetStatus(ctx context.Context) (r GetStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostLock implements post-lock operation.
//
// Post lock.
//
// POST /lock
func (UnimplementedHandler) PostLock(ctx context.Context) (r PostLockRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostUnlock implements post-unlock operation.
//
// Post unlock.
//
// POST /unlock
func (UnimplementedHandler) PostUnlock(ctx context.Context) (r PostUnlockRes, _ error) {
	return r, ht.ErrNotImplemented
}
