// Code generated by ogen, DO NOT EDIT.

package client

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetStatus implements get-status operation.
	//
	// Get status.
	//
	// GET /status
	GetStatus(ctx context.Context) (GetStatusRes, error)
	// PostLock implements post-lock operation.
	//
	// Post lock.
	//
	// POST /lock
	PostLock(ctx context.Context) (PostLockRes, error)
	// PostUnlock implements post-unlock operation.
	//
	// Post unlock.
	//
	// POST /unlock
	PostUnlock(ctx context.Context) (PostUnlockRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
