// Code generated by ogen, DO NOT EDIT.

package client

import (
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/json"
)

// setDefaults set default value of fields.
func (s *ErrorModel) setDefaults() {
	{
		val, _ := json.DecodeURI(jx.DecodeStr("\"about:blank\""))
		s.Type.SetTo(val)
	}
}
