// Code generated by ogen, DO NOT EDIT.
package client

type GetStatusRes interface {
	getStatusRes()
}

type PostLockRes interface {
	postLockRes()
}

type PostUnlockRes interface {
	postUnlockRes()
}
